config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'pages#index'

  # get '/index', to: 'pages#index'

  resources :todos

end

app/models/todo.rb
class Todo < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :todos

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
		
	end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
	before_action :authenticate_user!, except: [:index,:show]
	def index
		@todo = Todo.all
	end

	def new
		@todo = current_user.todos.build
	end

	def create
		@todo = current_user.todos.build(todo_params)
		if @todo.save
			redirect_to @todo

		else
			render 'edit'
		end
	end

	def show
		@todo = Todo.find(params[:id])
	end

	def edit
		
	end

	private

	def todo_params
		params.require(:todo).permit(:title)
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/todo_helper.rb
module TodoHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <p>&copy; Todoodle 2015</p>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Todoodle', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'All Blogs', todos_path %></li>
        <li><%= link_to 'Sign in', root_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/nav' %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-success' %>
<%= link_to 'Sign in', new_user_session_path, class: 'btn btn-danger' %>
<%= yield %>
<%= render 'layouts/footer' %>
<%= link_to 'Sign in', destroy_user_session_path, :method => :delete, class: 'btn btn-danger' %>

</body>
</html>

app/views/pages/index.html.erb
<h2 class="container">Hello</h2>

app/views/todos/_form.html.erb
<%= form_for @todo do |f| %>
	
	<% if @todo.errors.any? %>
		<h3>
			<%= pluralize(@todo.errors.count, 'error') %>
			prohibted this todo entry from being saved.
		</h3>
		<ul>
			<% @todo.errors.full_messages do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

	<p>
		<%= f.label :title %>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.submit 'Add to todo list', class: 'btn btn-sucess' %>
	</p>
<% end %>

app/views/todos/index.html.erb
<div class="container">
	<% @todo.each do |todo| %>
		<div class="todo-list">
			<div class="margin-left">
			<h4>Title</h4>
			<%= todo.title %>
			<h4>by user</h4>
			<%= todo.user.email %>
			</div>
		</div>
	<% end %>
</div>
<br>

app/views/todos/new.html.erb
<h1>Add todo</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<div class="container">
	<p>
		<h2>Title:</h2>
		<%= @todo.title %>
	</p>

</div>